name: monitoring
description: "A new Flutter project."
version: 1.0.0+1
environment:
  sdk: ">=3.4.1 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.6.0
  firebase_database: ^11.1.4
  http: ^1.2.2
  firebase_analytics: ^11.3.5
  url_launcher: ^6.1.7
  firebase_auth: ^5.3.3
  google_sign_in: ^6.2.2
  cloud_firestore: ^5.5.0
  intl: ^0.19.0
  path_provider: ^2.1.5
  share: ^2.0.4
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.3
  flutter_secure_storage: ^9.2.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - images/udang.png
